## Array manipulation (reshape,transpose,changing dims)

In [1]:
import numpy as np

In [2]:
# using shape - does affect the original array
arr1 = np.arange(15)
print(arr1)
arr1.shape = (3,5)
print('Using shape')
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Using shape
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
#using reshape - does not affect the original array ... must be initialized in another variable

#resizing the array using reshape but with the style of shape
arr2 = np.arange(15)
arr2.reshape(3,5)
print('\nUsing reshape sample 1')
print(arr2)


Using reshape sample 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
arr3 = np.arange(15)
reshaped_arr3 = arr3.reshape(3,5)
print('\nUsing reshape sample 2')
print(reshaped_arr3)


Using reshape sample 2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
print('\nFlatten the array')
arr4 = np.arange(15).reshape(3,5)
print(arr4)
print(arr4.ravel())
print(arr4.flatten(order='F'))


Flatten the array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


In [6]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
arr1.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [8]:
np.transpose(arr1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [9]:
arr1.shape

(3, 5)

In [10]:
np.array(arr1,ndmin=5)

array([[[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14]]]]])

In [11]:
arr1.ndim

2

In [12]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
np.expand_dims(arr1,axis=0)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [14]:
np.expand_dims(arr1,axis=0).shape

(1, 3, 5)

In [15]:
np.expand_dims(arr1,axis=1)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [16]:
np.expand_dims(arr1,axis=1).shape

(3, 1, 5)

In [17]:
np.expand_dims(arr1,axis=2)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [18]:
np.expand_dims(arr1,axis=1).shape

(3, 1, 5)