## Advanced Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(24).reshape(4,6)
print('Sample Array\n',arr1)

Sample Array
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [3]:
print('2nd row,3rd element: ',arr1[1,2])

2nd row,3rd element:  8


In [4]:
print('3rd row,2nd element and 2nd to the last element: ',arr1[2,[1,-2]])

3rd row,2nd element and 2nd to the last element:  [13 16]


In [5]:
print('3rd column until end:\n',arr1[:,2:])

3rd column until end:
 [[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]


In [6]:
print('\nFirst column and last column:\n',arr1[:,[0,-1]])


First column and last column:
 [[ 0  5]
 [ 6 11]
 [12 17]
 [18 23]]


In [7]:
print('\nElements in corners:\n',arr1[[[0],[-1]],[[0,-1],[0,-1]]])


Elements in corners:
 [[ 0  5]
 [18 23]]


In [8]:
arr1[:,[1,3,5]]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [9]:
arr1 = np.arange(24).reshape(4,6)

print('Sample Array\n',arr1)

print('\n2nd row,3rd element: ',arr1[1,2])
print('\n3rd row,2nd element and 2nd to the last element:\n',arr1[2,[1,-2]])
print('\n3rd column until end:\n',arr1[:,2:])
print('\nFirst column and last column:\n',np.transpose(np.hstack(arr1[:,[[0],[-1]]])))
print('\nElements in corners:\n',arr1[[[0],[-1]],[[0,-1],[0,-1]]])
print('\nOdd elements:\n',arr1[arr1%2!=0])

Sample Array
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

2nd row,3rd element:  8

3rd row,2nd element and 2nd to the last element:
 [13 16]

3rd column until end:
 [[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]

First column and last column:
 [[ 0  5]
 [ 6 11]
 [12 17]
 [18 23]]

Elements in corners:
 [[ 0  5]
 [18 23]]

Odd elements:
 [ 1  3  5  7  9 11 13 15 17 19 21 23]
