##  Iterating over numpy array

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(15).reshape(3,5)
print('Sample array:\n',arr1)
print()

Sample array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



In [5]:
for row in arr1:
    for element in row:
        print(element,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [8]:
for x in range(arr1.shape[1]):
    for y in range(arr1.shape[0]):
        print(arr1[y,x],end=' ')

0 5 10 1 6 11 2 7 12 3 8 13 4 9 14 

In [9]:
for i in np.nditer(arr1): 
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [10]:
for i in np.nditer(arr1,order='C'): 
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [11]:
for i in np.nditer(arr1,order='F'): 
    print(i,end=' ')

0 5 10 1 6 11 2 7 12 3 8 13 4 9 14 