## Joining and splitting array

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print('Note: There could be one or more arrays in the parameter. vstack and hstack does not need to specify the axis.\n')
print('First Array:\n',arr1)
print('Second Array:\n',arr2)

Note: There could be one or more arrays in the parameter. vstack and hstack does not need to specify the axis.

First Array:
 [[1 2]
 [3 4]]
Second Array:
 [[5 6]
 [7 8]]


In [3]:
print('\nConcatenate arrays in axis 0:\n',np.concatenate((arr1,arr2)))
print('\nConcatenate arrays in axis 1:\n',np.concatenate((arr1,arr2),axis=1))


Concatenate arrays in axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate arrays in axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [4]:
np.concatenate(arr1)

array([1, 2, 3, 4])

In [5]:
print('\nStacks\n')
print('stack: add a new axis\n',np.stack((arr1,arr2)))
print('\nvstack:\n',np.vstack((arr1,arr2)))
print('\nhstack:\n',np.hstack((arr1,arr2)))


Stacks

stack: add a new axis
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [6]:
arr3 = np.arange(1,13).reshape(3,4)
print('\nThird Array:\n',arr3)
print('\nconcatenate rows in third array using concatenate:\n',np.concatenate(arr3))
print('\nconcatenate rows in third array using hstack:\n',np.hstack(arr3))
print('\nJoining first and second array using append:\n',np.append(arr1,arr2))


Third Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

concatenate rows in third array using concatenate:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

concatenate rows in third array using hstack:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Joining first and second array using append:
 [1 2 3 4 5 6 7 8]


In [7]:
arr1 = np.arange(1,13)
print('Sample Array 1:\n',arr1)
print('\nSplitting the array into 3:\n',np.split(arr1,3))

Sample Array 1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Splitting the array into 3:
 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [8]:
np.array(np.split(arr1,3))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr2 = np.arange(1,17).reshape(4,4)
print('\nSample Array 2:\n',arr2)
print('\nSplitting the array using hsplit:\n',np.hsplit(arr2,2))
print('\nSplitting the array using vsplit:\n',np.vsplit(arr2,2))


Sample Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Splitting the array using hsplit:
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]

Splitting the array using vsplit:
 [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
