## Copy and Views

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = arr1

In [3]:
print('Array 1:\n',arr1)
print('\narr2 = arr1:')
print('\nArray 2:\n',arr2)

Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 = arr1:

Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
print('\nid(Array1):',id(arr1),'==','id(Array2):',id(arr2))


id(Array1): 2595408355696 == id(Array2): 2595408355696


In [5]:
print('Array 1 == Array 2: ',id(arr1)==id(arr2))

Array 1 == Array 2:  True


### View

In [6]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = arr1.view()

print('Array 1:\n',arr1)
print('\narr2 = arr1.view():')
print('\nArray 2:\n',arr2)
print('\nid(Array1):',id(arr1),'==','id(Array2):',id(arr2))
print('Array 1 == Array 2: ',id(arr1)==id(arr2))

Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 = arr1.view():

Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

id(Array1): 2595408425008 == id(Array2): 2595408425088
Array 1 == Array 2:  False


In [7]:
print('\nChange in the values in the array also changes the values of the original.')
print('\narr2[0]=[10,10,10,10]')
arr2[0]=[10,10,10,10]
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)


Change in the values in the array also changes the values of the original.

arr2[0]=[10,10,10,10]

Array 2:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 1:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print('\nBut change in dimensions of the array doesn’t change dimensions of the original.')

print('\narr2.shape = (2,6)')
arr2.shape = (2,6)
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)


But change in dimensions of the array doesn’t change dimensions of the original.

arr2.shape = (2,6)

Array 2:
 [[10 10 10 10  5  6]
 [ 7  8  9 10 11 12]]
Array 1:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Copy

In [9]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = arr1.copy()
print('Array 1:\n',arr1)
print('\narr2 = arr1.copy():')
print('\nArray 2:\n',arr2)
print('\nid(Array1):',id(arr1),'==','id(Array2):',id(arr2))
print('Array 1 == Array 2: ',id(arr1)==id(arr2))

Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 = arr1.copy():

Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

id(Array1): 2595408428208 == id(Array2): 2595408425008
Array 1 == Array 2:  False


In [10]:
print('\nChange in the values in the array doesn\'t changes the values of the original.')
print('\narr2[0]=[10,10,10,10]')
arr2[0]=[10,10,10,10]
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)


Change in the values in the array doesn't changes the values of the original.

arr2[0]=[10,10,10,10]

Array 2:
 [[10 10 10 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print('\nChange in dimensions of the array also doesn’t change dimensions of the original.')

print('\narr2.shape = (2,6)')
arr2.shape = (2,6)
print('\nArray 2:\n',arr2)
print('Array 1:\n',arr1)


Change in dimensions of the array also doesn’t change dimensions of the original.

arr2.shape = (2,6)

Array 2:
 [[10 10 10 10  5  6]
 [ 7  8  9 10 11 12]]
Array 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
