## Sorting and Searching

### Sort

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,101,size=(3,10))
print('Sample array:\n',arr1)

Sample array:
 [[ 3 47 70 84 99 96 38 26 14 49]
 [22 24 60 13 19 97 42 54 66 22]
 [88 32 17 45 33 99 65 84 24 91]]


In [3]:
print('\nSorting sample array (flatten it first):\n',np.sort(arr1.flatten()))


Sorting sample array (flatten it first):
 [ 3 13 14 17 19 22 22 24 24 26 32 33 38 42 45 47 49 54 60 65 66 70 84 84
 88 91 96 97 99 99]


In [4]:
print('\nSorting each row of sample array:\n',np.sort(arr1))


Sorting each row of sample array:
 [[ 3 14 26 38 47 49 70 84 96 99]
 [13 19 22 22 24 42 54 60 66 97]
 [17 24 32 33 45 65 84 88 91 99]]


In [5]:
print('\nSorting each column of sample array:\n',np.sort(arr1,axis=0))


Sorting each column of sample array:
 [[ 3 24 17 13 19 96 38 26 14 22]
 [22 32 60 45 33 97 42 54 24 49]
 [88 47 70 84 99 99 65 84 66 91]]


### Search

In [6]:
arr1 = np.random.randint(1,101,size=(3,10))
print('Sample array:\n',arr1)

Sample array:
 [[56 17  9 93 45  2 80 49  8 91]
 [44 46 85 78 66 86 79 57 46 35]
 [47 39 36 48 96 35 55 65 80 26]]


In [7]:
print('\nIndex of minimum element: (seen as flattened array)',np.argmin(arr1))


Index of minimum element: (seen as flattened array) 5


In [8]:
arr1.flatten()[24]

96

In [9]:
print('\nIndices of minimum element in each row: ',np.argmin(arr1,axis=1))
print('Indices of minimum element in each column: ',np.argmin(arr1,axis=0))


Indices of minimum element in each row:  [5 9 9]
Indices of minimum element in each column:  [1 0 0 2 0 0 2 0 0 2]


In [10]:
print('\nIndices of maximum element in each row: ',np.argmax(arr1,axis=1))
print('Indices of maximum element in each column: ',np.argmax(arr1,axis=0))


Indices of maximum element in each row:  [3 5 4]
Indices of maximum element in each column:  [0 1 1 0 2 1 0 2 2 0]


In [11]:
np.where(arr1>50)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 3, 6, 9, 2, 3, 4, 5, 6, 7, 4, 6, 7, 8], dtype=int64))

In [12]:
print('\nIndices of elements greater than 50:\n',np.where(arr1>50)[0],'\n',np.where(arr1>50)[1])


Indices of elements greater than 50:
 [0 0 0 0 1 1 1 1 1 1 2 2 2 2] 
 [0 3 6 9 2 3 4 5 6 7 4 6 7 8]


In [13]:
print('\nUsing arr[arr>50]:\n',arr1[arr1>50])


Using arr[arr>50]:
 [56 93 80 91 85 78 66 86 79 57 96 55 65 80]
